{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservice-api.fullname" . }}-secrets
  labels:
    {{- include "microservice-api.labels" . | nindent 4 }}
type: Opaque
data:
  database_password: {{ .Values.secrets.database.password | b64enc | quote }}
  api_key: {{ .Values.secrets.api.key | b64enc | quote }}
  jwt_secret: {{ .Values.secrets.api.jwtSecret | b64enc | quote }}
{{- end }}
